from antropometria.statistics.features_analysis import PCAAnalysis
from antropometria.statistics.mean import calculate_mean_from_dict
from antropometria.statistics.min_max_normalization import apply_min_max_normalization
from antropometria.statistics.pearson_correlation_feature_selector import PeasonCorrelationFeatureSelector
from antropometria.statistics.normality_tests import generate_histogram, perform_shapiro_wilk_test
from antropometria.statistics.friedman import apply_friedman
from antropometria.statistics.wilcoxon import apply_wilcoxon
