from antropometria.classifiers.KNearestNeighbors import KNearestNeighbors
from antropometria.classifiers.NaiveBayes import NaiveBayes
from antropometria.classifiers.NeuralNetwork import NeuralNetwork
from antropometria.classifiers.RandomForest import RandomForest
from antropometria.classifiers.SupportVectorMachine import SupportVectorMachine
